name: Daily Program & Brochure Reports

on:
  schedule:
    - cron: '30 12 * * *'  # 18:00 IST daily
  workflow_dispatch: {}     # allow manual run

jobs:
  run-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system packages (tesseract, etc)
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr libtesseract-dev

      - name: Write service_account.json from secret
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > service_account.json

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline (non-interactive)
        env:
          WORKDIR: ${{ github.workspace }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SKIP_SEMANTIC_VALIDATION: ${{ secrets.SKIP_SEMANTIC_VALIDATION }}
        run: |
          python final_program_data_sync.py

      - name: Send email with attachments
        env:
          WORKDIR: ${{ github.workspace }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        run: |
          python send_email.py
